### ISSUE TITLE
Will not build on Windows

### ISSUE THREAD

**Issue by serialhex** [zackehh/siphash-elixir#2]
Using the VS2015 x64 Native Tools Command Prompt I tried to manually compile (as Windows doesn't have a `make` utility, and `nmake` has different syntax) and got the following:

```
D:\programmin\Projects\elai\deps\siphash>cl -w -g -O3 -ansi -pedantic -Wall -I"C:\Program Files\erl9.0\erts-9.0\include" -o priv\siphash.so c_src\siphash.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
cl : Command line warning D9002 : ignoring unknown option '-g'
cl : Command line warning D9002 : ignoring unknown option '-O3'
cl : Command line warning D9002 : ignoring unknown option '-ansi'
cl : Command line warning D9002 : ignoring unknown option '-pedantic'
siphash.c
c:\program files\erl9.0\erts-9.0\include\erl_drv_nif.h(40): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member 'dirty_scheduler_support'
C:\Program Files\erl9.0\erts-9.0\include\erl_nif.h(103): warning C4820: 'enif_func_t': '4' bytes padding added after data member 'arity'
C:\Program Files\erl9.0\erts-9.0\include\erl_nif.h(105): warning C4820: 'enif_func_t': '4' bytes padding added after data member 'flags'
C:\Program Files\erl9.0\erts-9.0\include\erl_nif.h(114): warning C4820: 'enif_entry_t': '4' bytes padding added after data member 'num_of_funcs'
C:\Program Files\erl9.0\erts-9.0\include\erl_nif.h(127): warning C4820: 'enif_entry_t': '4' bytes padding added after data member 'options'
d:\programmin\projects\elai\deps\siphash\c_src\nif.h(9): warning C4100: 'argv': unreferenced formal parameter
d:\programmin\projects\elai\deps\siphash\c_src\nif.h(9): warning C4100: 'argc': unreferenced formal parameter
d:\programmin\projects\elai\deps\siphash\c_src\nif.h(13): warning C4100: 'info': unreferenced formal parameter
d:\programmin\projects\elai\deps\siphash\c_src\nif.h(13): warning C4100: 'old': unreferenced formal parameter
d:\programmin\projects\elai\deps\siphash\c_src\nif.h(13): warning C4100: 'new': unreferenced formal parameter
d:\programmin\projects\elai\deps\siphash\c_src\nif.h(13): warning C4100: 'env': unreferenced formal parameter
c_src\siphash.c(62): warning C4388: '<': signed/unsigned mismatch
c_src\siphash.c(89): warning C4242: 'function': conversion from 'uint64_t' to 'unsigned long', possible loss of data
c_src\siphash.c(97): warning C4057: 'function': 'char *const ' differs in indirection to slightly different base types from 'unsigned char *'
c_src\siphash.c(97): warning C4057: 'function': 'const char *const ' differs in indirection to slightly different base types from 'unsigned char *'
c_src\siphash.c(97): warning C4774: 'sprintf' : format string expected in argument 2 is not a string literal
c_src\siphash.c(97): note: e.g. instead of printf(name); use printf("%s", name); because format specifiers in 'name' may pose a security issue
c_src\siphash.c(97): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
c_src\siphash.c(108): warning C4013: 'memcpy' undefined; assuming extern returning int
c_src\siphash.c(109): warning C4710: 'int sprintf(char *const ,const char *const ,...)': function not inlined
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
Microsoft (R) Incremental Linker Version 14.00.24213.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:siphash.exe
/out:priv\siphash.so
siphash.obj
   Creating library priv\siphash.lib and object priv\siphash.exp
LINK : fatal error LNK1561: entry point must be defined
```

I had to take the `-Wextra` parameter out because that straight up broke `cl.exe`.  I'm having this issue because a library I depend on depends on this library.  Installing Cygwin or MinGW isn't really an option, as getting those to play nicely on my system (let alone with anything else on the system) is nearly impossible.

Thanks for any help!

**Comment by whitfin** [comment]
Hi @serialhex!

Unfortunately I don't have a Windows machine to test this, so it'll be a lot of guesswork. Are you on the Elixir Slack team?

I'm actually considering replacing the NIFs in this library with pure Elixir if I can get it to run fast enough. Previously I had bottlenecks but I think my Elixir has come along enough that I can gain a few performance improvements over what's there currently. This would remove your Windows issues, and make it easier to maintain.

**Comment by serialhex** [comment]
Yeah, this is a constant issue with nearly *any* open source project that has some C/C++ dependency.  Mostly because there isn't an easy way for Windows devs to just get all their include files into one general location and find the rest of the stuff there.  (I'm using a JSON as a database / key-value store as it would be too much to install anything, and it's also too much of a pain to get SQLITE to compile :angry: )

Maybe there is a way to have 2 install paths?  One that is your current implementation, and another that is pure Erlang/Elixir.  This way you can slowly get the native version to the near C version.  Just a suggestion...

**Comment by whitfin** [comment]
@serialhex that's actually the case now, you can use Elixir or C - the issue is that Mix will automatically try to compile the C code even if you're not using it. Shouldn't be an issue, I'll get to this ASAP for you.

**Comment by whitfin** [comment]
@serialhex the C library will still not build on Windows, need to figure that out going forwards. In the meantime, you can add this to your configurations (make sure to use v3.2.0 onwards):

```elixir
config :siphash,
  disable_nifs: true
```

This will allow you to use the pure Elixir implementation directly and skip the C compilation. Best I got for now.

**Comment by serialhex** [comment]
Sweet, thanks!  A workaround is better than no workaround.
